spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://root:tNMOB0W9ffsFBdWxlAKj@containers-us-west-132.railway.app:6346/railway?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=tNMOB0W9ffsFBdWxlAKj
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true

#JWT
jwt.secret = secret
jwt.expiration = 3600

#jdbc:mysql://localhost:3306/ap?useSSL=false&serverTimezone=UTC
