spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://u4xzaalmlfgq8ztz:E7WPkxfaVwZdewWUuT1i@bfkb1fjegxm7uffa7svi-mysql.services.clever-cloud.com:3306/bfkb1fjegxm7uffa7svi?useSSL=false&serverTimezone=UTC
spring.datasource.username=u4xzaalmlfgq8ztz
spring.datasource.password=E7WPkxfaVwZdewWUuT1i
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

#JWT
jwt.secret = secret
jwt.expiration = 3600

#jdbc:mysql://localhost:3306/ap?useSSL=false&serverTimezone=UTC
#jdbc:mysql://u4xzaalmlfgq8ztz:vFNr69kLkVFfPsccpxvv@bfkb1fjegxm7uffa7svi-mysql.services.clever-cloud.com:3306/bfkb1fjegxm7uffa7svi?useSSL=false&serverTimezone=UTC
#u4xzaalmlfgq8ztz
#E7WPkxfaVwZdewWUuT1i